---
- hosts: all
  become: true
  gather_facts: false
  vars:
    play_local_hosts: ["stage01","stage02"]
  #Build Inventory conditioning a new inventory which will be having only WebUser
  tasks:
    - name: Build inventory
      add_host:
        name: "{{ item }}"
        groups: to_do
      when: hostvars[item].prpc_node_type  == "WebUser"
      loop: "{{ play_local_hosts }}"

#Print host which is categorized as Webuser
- hosts: to_do
  tasks:
    - name: Print Server details
      debug:
          msg: "Running on {{ ansible_host }} with type {{ prpc_node_type }}"
      